from __future__ import annotations


class LangChain:
    """Custom span and log attribute keys for LangChain / LangGraph instrumentation."""

    SPAN_KIND = "langchain.span.kind"
    RUN_ID = "langchain.run.id"
    PARENT_RUN_ID = "langchain.run.parent_id"
    ROOT_RUN_ID = "langchain.run.root_id"
    RUN_TYPE = "langchain.run.type"
    SERIALIZED_CLASS = "langchain.serialized.class"
    SERIALIZED_ID = "langchain.serialized.id"
    SERIALIZED_NAME = "langchain.serialized.name"
    SERIALIZED_FORMAT = "langchain.serialized.format"
    WORKFLOW_NAME = "langchain.workflow.name"
    WORKFLOW_PROVIDER = "langchain.workflow.provider"
    LANGGRAPH_NODE = "langgraph.node"
    LANGGRAPH_COMMAND_SOURCE = "langgraph.command.source"
    LANGGRAPH_COMMAND_TARGET = "langgraph.command.target"
    TAGS = "langchain.tags"
    METADATA = "langchain.metadata"
    RAW_INPUT = "langchain.raw.input"
    RAW_OUTPUT = "langchain.raw.output"
    TOOL_CALLS = "langchain.tool.calls"
    INPUT_MESSAGES_COUNT = "langchain.input.messages.count"
    OUTPUT_MESSAGES_COUNT = "langchain.output.messages.count"
    CONTENT_BLOCK_COUNT = "langchain.content_block.count"
    USAGE_REASONING_TOKENS = "langchain.usage.reasoning_tokens"
    USAGE_AUDIO_INPUT_TOKENS = "langchain.usage.audio_input_tokens"
    USAGE_AUDIO_OUTPUT_TOKENS = "langchain.usage.audio_output_tokens"
    USAGE_CACHE_READ_TOKENS = "langchain.usage.cache_read_tokens"
    USAGE_CACHE_WRITE_TOKENS = "langchain.usage.cache_write_tokens"
    ERROR_CLASS = "langchain.error.class"
    ERROR_MESSAGE = "langchain.error.message"
    RESPONSE_STREAM_CHUNK_COUNT = "langchain.response.stream_chunk_count"
    RESPONSE_JSON_SCHEMA = "langchain.response.json_schema"
    PROVIDER_USAGE_SOURCE = "langchain.provider.usage_source"
    PROMPT_TEMPLATE = "langchain.prompt.template"
    PROMPT_TEMPLATE_VARIABLES = "langchain.prompt.template_variables"
    RETRIEVER_DOCUMENT_COUNT = "langchain.retriever.document_count"
    REDACTION_APPLIED = "langchain.redaction.applied"
    ASSOCIATION_PROPERTIES = "langchain.association.properties"
    ENTITY_NAME = "langchain.entity.name"
    ENTITY_PATH = "langchain.entity.path"
    ENTITY_VERSION = "langchain.entity.version"
    CALLBACK_NAME = "langchain.callback.name"
    CALLBACK_PHASE = "langchain.callback.phase"
    INPUT_VALUE = "input.value"
    INPUT_MIME_TYPE = "input.mime_type"
    OUTPUT_VALUE = "output.value"
    OUTPUT_MIME_TYPE = "output.mime_type"


class SpanKinds:
    CHAT_MODEL = "chat_model"
    WORKFLOW = "workflow"
    TOOL = "tool"
    CHAIN = "chain"
    LLM = "llm"
    RETRIEVER = "retriever"
    EMBEDDING = "embedding"
    AGENT = "agent"
    RERANKER = "reranker"
    UNKNOWN = "unknown"
    GUARDRAIL = "guardrail"
    EVALUATOR = "evaluator"
    PROMPT = "prompt"


class MimeTypes:
    JSON = "application/json"
    TEXT = "text/plain"
